# CircleCI 2.0 configuration file
version: 2
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:14.15.0-browsers
jobs:
  build-bundle:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-bundle-dependencies-{{ checksum "bundle/package-lock.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-bundle-dependencies-
      - run: cd bundle && npm install
      - run: cd bundle && npm run build
      - save_cache:
          paths:
            - bundle/node_modules
          key: v1-bundle-dependencies-{{ checksum "bundle/package-lock.json" }}
      - persist_to_workspace: 
          root: .
          paths:
            - bundle/node_modules
            - bundle/apidocs
            - bundle/build
            - bundle/dist
  test-bundle:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Unit Tests
          command: cd bundle && (npm run test || touch failure.marker)
      - store_test_results:
          path: bundle/coverage/junit
      - store_artifacts:
          path: bundle/coverage
      # disabled, since we upload codecov already via github actions
      # - run:
      #     name: Upload Coverage Data to Codecov
      #     command: bash <(curl -s https://codecov.io/bash) -F material,unittest
      - run:
          name: Check for Test Failures
          command: if [ -f bundle/failure.marker ] ; then exit 127; else exit 0; fi
  # publish-bundle:
  #   <<: *defaults
  #   steps:
  #     - checkout
  #     - attach_workspace:
  #         at: .
  #     - run:
  #         name: Add README to bundle
  #         command: cp README.md bundle/README.md
  #     - run:
  #         name: Authenticate with NPM
  #         command: cd bundle && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
  #     - run:
  #         name: Publish Blox Material
  #         command: cd bundle && npm publish --tag beta

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-bundle:
          filters:
            tags:
              only: /.*/
      - test-bundle:
          requires:
            - build-bundle
          filters:
            tags:
              only: /.*/
      # - publish-bundle:
      #     requires:
      #       - test-bundle
      #     filters:
      #       tags:
      #         only: /^v[0-9]+(\.[0-9]+)*([-].*)?$/
      #       branches:
      #         ignore: /.*/
